// packages/react/countries/base/Eh.tsx
// SPDX-License-Identifier: GPL-3.0-only
// Commercial license available at https://geoicons.io
import { useId } from 'react';
import type { SVGProps } from 'react';
import { noteIconRender } from '@geoicons/core';

interface Props extends SVGProps<SVGSVGElement> {
  size?: number | string;
  strokeWidth?: number;
}

export const Eh = ({
  size = 24,
  strokeWidth = 1,
  'aria-label': ariaLabel,
  role,
  ...props
}: Props) => {
  const uid = useId();
  // Compliance nudge: warns once if icons render without a licensed <IconProvider>.
  // noteIconRender is a plain guarded fn (no client-only React API), so it does NOT
  // taint this as a Client Component — it no-ops on the server (window guard) and
  // only schedules a deferred client-side check. Do NOT wrap in useEffect (that would
  // force "use client" and break RSC/SSG consumers like the site).
  noteIconRender();
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      stroke="currentColor"
      strokeWidth={strokeWidth}
      fill="none"
      role={ariaLabel ? (role ?? 'img') : role}
      aria-labelledby={ariaLabel ? `${uid}-title` : undefined}
      aria-hidden={ariaLabel ? undefined : true}
      {...props}
    >
      {ariaLabel && <title id={`${uid}-title`}>{ariaLabel}</title>}
      <path strokeLinejoin="round" d="M11.62 20.987H1.2l.247-1.839a.5.5 0 0 1 .188-.327l.971-.759a.5.5 0 0 0 .166-.23l1.165-3.384a.5.5 0 0 1 .11-.18L6.56 11.61a.5.5 0 0 0 .124-.23l.925-3.952a.5.5 0 0 1 .24-.32L9.914 5.93a.5.5 0 0 0 .216-.245l1.092-2.673H22.8v4.752h-8.56v7.282l-3.017 1.523z"/>
    </svg>
  );
};

// packages/angular/countries/Eh.ts
// SPDX-License-Identifier: GPL-3.0-only
// Commercial license available at https://geoicons.io
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { NgIf } from '@angular/common';
import { GeoIconBase } from '@geoicons/angular';

@Component({
  selector: 'geoicon-eh',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgIf],
  hostDirectives: [
    {
      directive: GeoIconBase,
      inputs: ['size', 'strokeWidth', 'stroke', 'fill', 'aria-label'],
    },
  ],
  template: `<svg viewBox="0 0 24 24" [attr.width]="b.size" [attr.height]="b.size" [attr.stroke]="b.stroke" [attr.stroke-width]="b.strokeWidth" [attr.fill]="b.fill" [attr.role]="b.ariaLabel ? 'img' : null" [attr.aria-labelledby]="b.ariaLabel ? b.titleId : null" [attr.aria-hidden]="b.ariaLabel ? null : 'true'"><title *ngIf="b.ariaLabel" [id]="b.titleId">{{ b.ariaLabel }}</title><path stroke-linejoin="round" d="M11.62 20.987H1.2l.247-1.839a.5.5 0 0 1 .188-.327l.971-.759a.5.5 0 0 0 .166-.23l1.165-3.384a.5.5 0 0 1 .11-.18L6.56 11.61a.5.5 0 0 0 .124-.23l.925-3.952a.5.5 0 0 1 .24-.32L9.914 5.93a.5.5 0 0 0 .216-.245l1.092-2.673H22.8v4.752h-8.56v7.282l-3.017 1.523z"/></svg>`,
})
export class Eh {
  protected readonly b = inject(GeoIconBase);
}
