// packages/react/countries/base/Va.tsx
// SPDX-License-Identifier: GPL-3.0-only
// Commercial license available at https://geoicons.io
import { useId } from 'react';
import type { SVGProps } from 'react';
import { noteIconRender } from '@geoicons/core';

interface Props extends SVGProps<SVGSVGElement> {
  size?: number | string;
  strokeWidth?: number;
}

export const Va = ({
  size = 24,
  strokeWidth = 1,
  'aria-label': ariaLabel,
  role,
  ...props
}: Props) => {
  const uid = useId();
  // Compliance nudge: warns once if icons render without a licensed <IconProvider>.
  // noteIconRender is a plain guarded fn (no client-only React API), so it does NOT
  // taint this as a Client Component — it no-ops on the server (window guard) and
  // only schedules a deferred client-side check. Do NOT wrap in useEffect (that would
  // force "use client" and break RSC/SSG consumers like the site).
  noteIconRender();
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      stroke="currentColor"
      strokeWidth={strokeWidth}
      fill="none"
      role={ariaLabel ? (role ?? 'img') : role}
      aria-labelledby={ariaLabel ? `${uid}-title` : undefined}
      aria-hidden={ariaLabel ? undefined : true}
      {...props}
    >
      {ariaLabel && <title id={`${uid}-title`}>{ariaLabel}</title>}
      <path strokeLinejoin="round" d="m6.998 9.2-.44 3.119L1.2 16.036l2.018.894 1.298 1.012a.5.5 0 0 1 .138.169l.371.732a.5.5 0 0 0 .53.267l.811-.138a.5.5 0 0 0 .415-.454l.051-.658 3.454.558v1.059l6.069.67-.443-2.723 3.421-.494c2.51 2.999 5.2-2.03 2.015-3.764l.266-5.816-3.345-1.103-.418-2.395-6.504 2.395-.831-.686-1.029.268-.436.826.436.885-1.311 1.41z"/>
    </svg>
  );
};

// packages/angular/countries/Va.ts
// SPDX-License-Identifier: GPL-3.0-only
// Commercial license available at https://geoicons.io
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { NgIf } from '@angular/common';
import { GeoIconBase } from '@geoicons/angular';

@Component({
  selector: 'geoicon-va',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgIf],
  hostDirectives: [
    {
      directive: GeoIconBase,
      inputs: ['size', 'strokeWidth', 'stroke', 'fill', 'aria-label'],
    },
  ],
  template: `<svg viewBox="0 0 24 24" [attr.width]="b.size" [attr.height]="b.size" [attr.stroke]="b.stroke" [attr.stroke-width]="b.strokeWidth" [attr.fill]="b.fill" [attr.role]="b.ariaLabel ? 'img' : null" [attr.aria-labelledby]="b.ariaLabel ? b.titleId : null" [attr.aria-hidden]="b.ariaLabel ? null : 'true'"><title *ngIf="b.ariaLabel" [id]="b.titleId">{{ b.ariaLabel }}</title><path stroke-linejoin="round" d="m6.998 9.2-.44 3.119L1.2 16.036l2.018.894 1.298 1.012a.5.5 0 0 1 .138.169l.371.732a.5.5 0 0 0 .53.267l.811-.138a.5.5 0 0 0 .415-.454l.051-.658 3.454.558v1.059l6.069.67-.443-2.723 3.421-.494c2.51 2.999 5.2-2.03 2.015-3.764l.266-5.816-3.345-1.103-.418-2.395-6.504 2.395-.831-.686-1.029.268-.436.826.436.885-1.311 1.41z"/></svg>`,
})
export class Va {
  protected readonly b = inject(GeoIconBase);
}
