// packages/angular/countries/Wf.ts
// SPDX-License-Identifier: GPL-3.0-only
// Commercial license available at https://geoicons.io
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { NgIf } from '@angular/common';
import { GeoIconBase } from '@geoicons/angular';

@Component({
  selector: 'geoicon-wf',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgIf],
  hostDirectives: [
    {
      directive: GeoIconBase,
      inputs: ['size', 'strokeWidth', 'stroke', 'fill', 'aria-label'],
    },
  ],
  template: `<svg viewBox="0 0 24 24" [attr.width]="b.size" [attr.height]="b.size" [attr.stroke]="b.stroke" [attr.stroke-width]="b.strokeWidth" [attr.fill]="b.fill" [attr.role]="b.ariaLabel ? 'img' : null" [attr.aria-labelledby]="b.ariaLabel ? b.titleId : null" [attr.aria-hidden]="b.ariaLabel ? null : 'true'"><title *ngIf="b.ariaLabel" [id]="b.titleId">{{ b.ariaLabel }}</title><path stroke-linejoin="round" d="M6.722 17.747 3.36 15.208a1 1 0 0 0-1.525.414l-.332.796a1 1 0 0 0 .334 1.192l2.996 2.187a1 1 0 0 0 1.127.035l.697-.443a1 1 0 0 0 .065-1.642ZM19.704 4.823 18.86 6.56a1 1 0 0 0 .534 1.367l1.22.48a1 1 0 0 0 1.3-.577l.6-1.58a1 1 0 0 0-.39-1.193l-.975-.637a1 1 0 0 0-1.446.402Z"/></svg>`,
})
export class Wf {
  protected readonly b = inject(GeoIconBase);
}

// packages/react/countries/base/Wf.tsx
// SPDX-License-Identifier: GPL-3.0-only
// Commercial license available at https://geoicons.io
import { useId } from 'react';
import type { SVGProps } from 'react';
import { noteIconRender } from '@geoicons/core';

interface Props extends SVGProps<SVGSVGElement> {
  size?: number | string;
  strokeWidth?: number;
}

export const Wf = ({
  size = 24,
  strokeWidth = 1,
  'aria-label': ariaLabel,
  role,
  ...props
}: Props) => {
  const uid = useId();
  // Compliance nudge: warns once if icons render without a licensed <IconProvider>.
  // noteIconRender is a plain guarded fn (no client-only React API), so it does NOT
  // taint this as a Client Component — it no-ops on the server (window guard) and
  // only schedules a deferred client-side check. Do NOT wrap in useEffect (that would
  // force "use client" and break RSC/SSG consumers like the site).
  noteIconRender();
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      stroke="currentColor"
      strokeWidth={strokeWidth}
      fill="none"
      role={ariaLabel ? (role ?? 'img') : role}
      aria-labelledby={ariaLabel ? `${uid}-title` : undefined}
      aria-hidden={ariaLabel ? undefined : true}
      {...props}
    >
      {ariaLabel && <title id={`${uid}-title`}>{ariaLabel}</title>}
      <path strokeLinejoin="round" d="M6.722 17.747 3.36 15.208a1 1 0 0 0-1.525.414l-.332.796a1 1 0 0 0 .334 1.192l2.996 2.187a1 1 0 0 0 1.127.035l.697-.443a1 1 0 0 0 .065-1.642ZM19.704 4.823 18.86 6.56a1 1 0 0 0 .534 1.367l1.22.48a1 1 0 0 0 1.3-.577l.6-1.58a1 1 0 0 0-.39-1.193l-.975-.637a1 1 0 0 0-1.446.402Z"/>
    </svg>
  );
};
