// packages/angular/subdivisions/CaNorthwestTerritories.ts
// SPDX-License-Identifier: GPL-3.0-only
// Commercial license available at https://geoicons.io
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { NgIf } from '@angular/common';
import { GeoIconBase } from '@geoicons/angular';

@Component({
  selector: 'geoicon-ca-northwest-territories',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgIf],
  hostDirectives: [
    {
      directive: GeoIconBase,
      inputs: ['size', 'strokeWidth', 'stroke', 'fill', 'aria-label'],
    },
  ],
  template: `<svg viewBox="0 0 24 24" [attr.width]="b.size" [attr.height]="b.size" [attr.stroke]="b.stroke" [attr.stroke-width]="b.strokeWidth" [attr.fill]="b.fill" [attr.role]="b.ariaLabel ? 'img' : null" [attr.aria-labelledby]="b.ariaLabel ? b.titleId : null" [attr.aria-hidden]="b.ariaLabel ? null : 'true'"><title *ngIf="b.ariaLabel" [id]="b.titleId">{{ b.ariaLabel }}</title><path stroke-linejoin="round" d="M5.831 15.76a1 1 0 0 1 .597-.936l2.196-.965a1 1 0 0 1 .738-.027l1.847.659a.6.6 0 0 1 .398.581l-.022.82a.8.8 0 0 0 .315.66l2.67 2.03a2 2 0 0 0 .763.357l2.383.547a.6.6 0 0 1 .466.587l-.006 2.125a.6.6 0 0 1-.605.598l-6.644-.046a1 1 0 0 1-.745-.34l-4.074-4.64a1 1 0 0 1-.248-.64z"/></svg>`,
})
export class CaNorthwestTerritories {
  protected readonly b = inject(GeoIconBase);
}

// packages/react/subdivisions/base/CaNorthwestTerritories.tsx
// SPDX-License-Identifier: GPL-3.0-only
// Commercial license available at https://geoicons.io
import { useId } from 'react';
import type { SVGProps } from 'react';
import { noteIconRender } from '@geoicons/core';

interface Props extends SVGProps<SVGSVGElement> {
  size?: number | string;
  strokeWidth?: number;
}

export const CaNorthwestTerritories = ({
  size = 24,
  strokeWidth = 1,
  'aria-label': ariaLabel,
  role,
  ...props
}: Props) => {
  const uid = useId();
  // Compliance nudge: warns once if icons render without a licensed <IconProvider>.
  // noteIconRender is a plain guarded fn (no client-only React API), so it does NOT
  // taint this as a Client Component — it no-ops on the server (window guard) and
  // only schedules a deferred client-side check. Do NOT wrap in useEffect (that would
  // force "use client" and break RSC/SSG consumers like the site).
  noteIconRender();
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      stroke="currentColor"
      strokeWidth={strokeWidth}
      fill="none"
      role={ariaLabel ? (role ?? 'img') : role}
      aria-labelledby={ariaLabel ? `${uid}-title` : undefined}
      aria-hidden={ariaLabel ? undefined : true}
      {...props}
    >
      {ariaLabel && <title id={`${uid}-title`}>{ariaLabel}</title>}
      <path strokeLinejoin="round" d="M5.831 15.76a1 1 0 0 1 .597-.936l2.196-.965a1 1 0 0 1 .738-.027l1.847.659a.6.6 0 0 1 .398.581l-.022.82a.8.8 0 0 0 .315.66l2.67 2.03a2 2 0 0 0 .763.357l2.383.547a.6.6 0 0 1 .466.587l-.006 2.125a.6.6 0 0 1-.605.598l-6.644-.046a1 1 0 0 1-.745-.34l-4.074-4.64a1 1 0 0 1-.248-.64z"/>
    </svg>
  );
};
