// packages/angular/subdivisions/UsNebraska.ts
// SPDX-License-Identifier: GPL-3.0-only
// Commercial license available at https://geoicons.io
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { NgIf } from '@angular/common';
import { GeoIconBase } from '@geoicons/angular';

@Component({
  selector: 'geoicon-us-nebraska',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgIf],
  hostDirectives: [
    {
      directive: GeoIconBase,
      inputs: ['size', 'strokeWidth', 'stroke', 'fill', 'aria-label'],
    },
  ],
  template: `<svg viewBox="0 0 24 24" [attr.width]="b.size" [attr.height]="b.size" [attr.stroke]="b.stroke" [attr.stroke-width]="b.strokeWidth" [attr.fill]="b.fill" [attr.role]="b.ariaLabel ? 'img' : null" [attr.aria-labelledby]="b.ariaLabel ? b.titleId : null" [attr.aria-hidden]="b.ariaLabel ? null : 'true'"><title *ngIf="b.ariaLabel" [id]="b.titleId">{{ b.ariaLabel }}</title><path stroke-linejoin="round" d="M1.5 7.05a.3.3 0 0 0-.3.3v6.05a.3.3 0 0 0 .3.3l4.34-.01a.3.3 0 0 1 .3.3v2.65a.3.3 0 0 0 .3.3l15.825.01a.3.3 0 0 0 .257-.456l-.867-1.423a2 2 0 0 1-.292-.978l-.05-1.6a2 2 0 0 0-.156-.715l-1.181-2.795a1 1 0 0 0-.628-.567l-4.285-1.312a1 1 0 0 0-.292-.044z"/></svg>`,
})
export class UsNebraska {
  protected readonly b = inject(GeoIconBase);
}

// packages/react/subdivisions/base/UsNebraska.tsx
// SPDX-License-Identifier: GPL-3.0-only
// Commercial license available at https://geoicons.io
import { useId } from 'react';
import type { SVGProps } from 'react';
import { noteIconRender } from '@geoicons/core';

interface Props extends SVGProps<SVGSVGElement> {
  size?: number | string;
  strokeWidth?: number;
}

export const UsNebraska = ({
  size = 24,
  strokeWidth = 1,
  'aria-label': ariaLabel,
  role,
  ...props
}: Props) => {
  const uid = useId();
  // Compliance nudge: warns once if icons render without a licensed <IconProvider>.
  // noteIconRender is a plain guarded fn (no client-only React API), so it does NOT
  // taint this as a Client Component — it no-ops on the server (window guard) and
  // only schedules a deferred client-side check. Do NOT wrap in useEffect (that would
  // force "use client" and break RSC/SSG consumers like the site).
  noteIconRender();
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      stroke="currentColor"
      strokeWidth={strokeWidth}
      fill="none"
      role={ariaLabel ? (role ?? 'img') : role}
      aria-labelledby={ariaLabel ? `${uid}-title` : undefined}
      aria-hidden={ariaLabel ? undefined : true}
      {...props}
    >
      {ariaLabel && <title id={`${uid}-title`}>{ariaLabel}</title>}
      <path strokeLinejoin="round" d="M1.5 7.05a.3.3 0 0 0-.3.3v6.05a.3.3 0 0 0 .3.3l4.34-.01a.3.3 0 0 1 .3.3v2.65a.3.3 0 0 0 .3.3l15.825.01a.3.3 0 0 0 .257-.456l-.867-1.423a2 2 0 0 1-.292-.978l-.05-1.6a2 2 0 0 0-.156-.715l-1.181-2.795a1 1 0 0 0-.628-.567l-4.285-1.312a1 1 0 0 0-.292-.044z"/>
    </svg>
  );
};
